# Generated by Django 4.2.7 on 2023-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_eventos_asistentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
