# Generated by Django 4.2.7 on 2023-11-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
